### ISSUE TITLE
uDdbg: Debugger cannot run in AFL!

### ISSUE THREAD

**Issue by jannetele** [fgsect/unicorefuzz#19]
The debugger is not working as expected. I am running a single testcase using `python3 ucf emu -d testcase`. But it returns  the following:

```
[*] Loading debugger...
[*] Module core_module loaded
[*] Module mappings_module loaded
[*] Module memory_module loaded
[*] Module registers_module loaded
[*] Module patches_module loaded
[*] Module asm_module loaded
[*] Module configs_module loaded
[*] Module executors_module loaded
[*] Module module_find loaded
[*] Module stepover_module loaded
Traceback (most recent call last):
  File "ucf", line 335, in <module>
    args.function(args)
  File "ucf", line 67, in emulate
    Harness(load_conf(args)).harness(
  File "/unicorefuzz/unicorefuzz/harness.py", line 144, in harness
    self.uc_debug(uc, input_file, exits)
  File "/unicorefuzz/unicorefuzz/harness.py", line 233, in uc_debug
    raise Exception(
Exception: Debugger cannot run in AFL! Did you mean -t instead of -d?
```

The condition here https://github.com/fgsect/unicorefuzz/blob/master/unicorefuzz/harness.py#L232 returns `2` (`UC_AFL_RET_NO_AFL`). A single testcase without `-d` works fine.

**Comment by domenukk** [comment]
Ah, nice find! Looks like the underlying api changed.
Can you try if it's fixed with the latest commit? I don't have a working setup on my machine right now.

**Comment by jannetele** [comment]
It should be `if uc.afl_forkserver_start(exits) != UC_AFL_RET_NO_AFL:`. 
```
Traceback (most recent call last):                                                                                                                                                                                                             
  File "ucf", line 335, in <module>                                                                                                                                                                                                            
    args.function(args)                                                                                                                                                                                                                        
  File "ucf", line 67, in emulate                                                                                                                                                                                                              
    Harness(load_conf(args)).harness(                                                                                                                                                                                                          
  File "/unicorefuzz/unicorefuzz/harness.py", line 144, in harness
    self.uc_debug(uc, input_file, exits)
  File "/unicorefuzz/unicorefuzz/harness.py", line 232, in uc_debug
    if uc.afl_forkserver_start(exits) != uc.UC_AFL_RET_NO_AFL:
AttributeError: 'Uc' object has no attribute 'UC_AFL_RET_NO_AFL'
root@c61ad7da4946:/unicorefuzz# vim /unicorefuzz/unicorefuzz/harness.py
```

Also, when I use `if uc.afl_forkserver_start(exits) != UC_AFL_RET_NO_AFL:`, it returns the following:

```
[*] Loading debugger...
[*] Module core_module loaded
[*] Module mappings_module loaded
[*] Module memory_module loaded
[*] Module registers_module loaded
[*] Module patches_module loaded
[*] Module asm_module loaded
[*] Module configs_module loaded
[*] Module executors_module loaded
[*] Module module_find loaded
[*] Module stepover_module loaded
Traceback (most recent call last):
  File "ucf", line 335, in <module>
    args.function(args)
  File "ucf", line 67, in emulate
    Harness(load_conf(args)).harness(
  File "/unicorefuzz/unicorefuzz/harness.py", line 144, in harness
    self.uc_debug(uc, input_file, exits)
  File "/unicorefuzz/unicorefuzz/harness.py", line 247, in uc_debug
    exit_point = self.exits[0]
TypeError: 'NoneType' object is not subscriptable
```

It does not set the `exits` array.

**Comment by domenukk** [comment]
All right seems like I'll have to get my test setup running again. :)
For the exits, did you correctly set exits in your config?

**Comment by jannetele** [comment]
Here is my `config.py`

```python
# A place to put scratch memory to. Non-kernelspace address should be fine.
SCRATCH_ADDR = 0x80000
# How much scratch to add. We don't ask for much. Default should be fine.
SCRATCH_SIZE = 0x1000

# The page size used by the emulator. Optional.
PAGE_SIZE = 0x1000

# Set a supported architecture
ARCH = "x86"

# The gdb port to connect to
GDB_HOST = "192.168.101.2"
GDB_PORT = 1234

# Either set this to load the module from the VM and break at module + offset...
#MODULE = "procfs1"
#BREAK_OFFSET = 0x10

# Or this to break at a fixed offset.
BREAK_ADDR = 0x10037ef8
# You cannot set MODULE and BREAKOFFSET at the same time

# Additional exits here.
# The Exit at entry + LENGTH will be added automatically.
EXITS = [0x10081368]
# Exits realtive to the initial rip (entrypoint + addr)
ENTRY_RELATIVE_EXITS = []

# The location used to store data and logs
WORKDIR = os.path.join(os.getcwd(), "unicore_workdir")

# Where AFL input should be read from
AFL_INPUTS = os.path.join(os.getcwd(), "afl_inputs")
# Where AFL output should be placed at
AFL_OUTPUTS = os.path.join(os.getcwd(), "afl_outputs")

# Optional AFL dictionary
AFL_DICT = None
```
I think that should be correct right?

**Comment by domenukk** [comment]
Yeah looks fine. I'll set up my testbed again in the next few days. sorry :)

**Comment by jannetele** [comment]
No problem, i'll also take a look at it!

**Comment by domenukk** [comment]
Else you can try an older commit before the afl++ updates, for example 149fd552f6a36c48ca58a9e64e67e248674613a6
